spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:UserService/user-service-app/.env[.properties]
  application:
    name: user-service-app
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.resend.com
    port: 587
    username: resend
    password: ${RESEND_API_KEY:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    rest-template:
      enabled: true
    webclient:
      enabled: false
    restclient:
      enabled: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false

admin:
  usernames: ${ADMIN_USERNAMES:}
  passwords: ${ADMIN_PASSWORDS:}

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour in milliseconds


